name: '[Weekly - Updating question data files]'

on:
    # Change to 0 UTC Sunday for weekly updates later 
    schedule:
    - cron: "0 5 * * 0"    # runs at 5AM UTC ON SUNDAY to occur
                           # slightly after the weekly contest finishes

    # Allows for manual runs
    workflow_dispatch:


permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the current repository content
              uses: actions/checkout@v2

            - name: Setup python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip"


              # Dependencies for the markdown generator
            - name: Install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r 'requirements.txt'


            - name: Execute the markdown generation python script
              run: python query.py -a

            - name: Commit updated markdown files to repo
              run: |
                  git config --global user.name "Zanger67/query-data"
                  git config --global user.email "Zanger67[bot]@Zanger67.github.io"
                  git add .
                  git commit -m 'Updated question data' || exit 0
                  git push
